
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=algafood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev@123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d algafood"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local